name: meal_management
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.10.1
  firebase_database: ^10.2.7
  firebase_messaging: ^14.6.5
  flutter_easyloading: ^3.0.5
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  eva_icons_flutter: ^3.1.0
  intl: ^0.18.1
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
